### PR TITLE
add error message and loaders to screens and tabs

### PR DESCRIPTION
**Pull request by kyltec**

### CODE REVIEW

**Review by siddharthparmar7 — CHANGES_REQUESTED** [review]
Please resolve merge conflicts.

**Comment by kyltec** [comment]
resolved

**Review by siddharthparmar7 — CHANGES_REQUESTED** [review]
Please resolve merge conflicts.

**Comment by kyltec** [comment]
resolved

**Review by siddharthparmar7 — APPROVED** [review]

**Pull request merged**
